### ISSUE TITLE
Produce dataverse example

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/datalad-concepts#100]
E.g. my PhD project dataset, which has both contextual metadata on the dataset-level, and file-level metadata

- dataset: https://dataverse.nl/dataverse/rt-me-fmri
- json export: https://dataverse.nl/api/datasets/export?exporter=dataverse_json&persistentId=doi%3A10.34894/R1TNL8
- datacite xml export: https://dataverse.nl/api/datasets/export?exporter=Datacite&persistentId=doi%3A10.34894/R1TNL8
- jsonld export: https://dataverse.nl/api/datasets/export?exporter=schema.org&persistentId=doi%3A10.34894/R1TNL8

What's interesting about this dataset is that the file downloads are locked by default for the public. Users first need create a dataverseNL account and then request access via dataverse, they are then sent a data use agreement via email, which they have to sign and then send back via email, after which they are granted access via dataverseNL.

**Comment by mih** [comment]
Done via #101
