### ISSUE TITLE
Require semantic mapping for anything

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-concepts#24]
Looking into #19 it is clear that proper semantic annotation is critical. Therefore I propose the following rules:

- any ontology component must have a `class_uri` or `slot_uri` that points to an external definition (i.e., a definition that is not in our ontology)
- if an external definition is not available, a comment annotation must explain the nature of this uniqueness (this could be a hint that the modeling uses too complex concepts, and that an alternative approach should be sought)
- beyond a main definition, concepts should be annotated with as many mapping to common ontologies as possible. Not only exact mappings are of interest

**Comment by jsheunis** [comment]
Regarding: 

> if an external definition is not available, a comment annotation must explain the nature of this uniqueness (this could be a hint that the modeling uses too complex concepts, and that an alternative approach should be sought)

https://linkml.io/linkml/schemas/annotations.html#annotations provides several options for annotations of schema elements. In addition to the transformation of data between schemas supported via mappings, annotations could also be useful for applications that interpret and use schema information, see https://linkml.io/linkml/developers/tool-developer-guide.html#customizing-and-application-hints.

**Comment by mih** [comment]
I believe this is resolved now
