### ISSUE TITLE
Comparison of vocabularies for data use consent / access / restrictions / conditions

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/datalad-concepts#58]
- Data Use Ontology: https://github.com/EBISPOT/DUO
- Data Privacy Vocabulary: https://w3c.github.io/dpv/dpv/ (has several possibly useful extensions, e.g. gdpr or pd extensions)
- Informed Consent: https://github.com/ICO-ontology/ICO
- GConsent - A consent ontology based on the GDPR: https://openscience.adaptcentre.ie/ontologies/GConsent/docs/ontology
- Open Digital Rights Language (ODRL): https://www.w3.org/TR/odrl-vocab/

**Comment by mih** [comment]
Closing this info issue in favor of #149
