### ISSUE TITLE
Map the HCLS community profile description onto a datalad dataset

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/datalad-concepts#60]
Initial comments by @mih:

> The [HCLS dataset description specification](https://www.w3.org/TR/hcls-dataset/) appears to provide a range of required concepts that are missing in RO-crates. Importantly, this includes:
> - Distinction of summary-level, version-level, and distribution-level entities that could be mapped onto evolving datasets with multiple versions that are deposited in multiple locations.
>
> The HCLS specification appears to be more geared towards a-file-as-a-dataset use cases. However, the aforementioned distinctions could be combined with the single-version-single-location use case of RO-crates to create a more appropriate, more comprehensive description of DataLad datasets

**Comment by mih** [comment]
I believe that we have now settled on a schema that can express all this, with a relatively minimalistic setup.
