### ISSUE TITLE
List of useful ontologies and their purposes

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/datalad-concepts#62]
Towards providing a comprehensive description of all ontologies/vocabularies/lists of terms that we will eventually import into our data model.

#### _dcat_:  Data Catalog ontology
- https://www.w3.org/TR/vocab-dcat-3/

#### _schema_: schema.org
- https://schema.org/

#### _prov_: Provenance Ontology
- https://www.w3.org/TR/prov-o/

#### _skos_: Simple Knowledge Organization System
- https://www.w3.org/TR/skos-reference/

#### _dcmterms_: Dublin Core DCMI Metadata Terms
- https://www.dublincore.org/specifications/dublin-core/dcmi-terms/

#### _odrl_: Open Digital Rights Language (ODRL) Ontology
- https://www.w3.org/ns/odrl/2/

#### _dcpac_: Data Catalog – Provenance – Access Control (DCPAC) Ontology 
- The DCPAC ontology aligns the DCAT ontology with the ODRL ontology by declaring the classes
`dcat:Distribution` and `dcat:Resource` to be subclasses of `odrl:Asset`. With `odrl:Asset` representing a resource
or a collection of resources that are the subject of access authorization rules, this enables the definition of access control permissions for these DCAT classes and subclasses with the ODRL vocabulary.
- the DCPAC ontology extends the DCAT ontology by defining various types of `dcat:Dataset` subclasses, which allows for distinguishing different types of datasets in a data lake, such as raw data files, tabular data files, relational database and graph database resources.
- The PROV-O class `prov:Agent` is declared as subclass of `odrl:Party`, hence enabling all instances of `prov:Agent` to undertake roles in access control permissions.
- The DCPAC ontology defines new subclasses of `prov:Activity`, which allow for distinguishing different types of activities that created (`dcpac:GenerationActivity`) or modified (`dcpac:ModificationActivity`) a data lake resource.

**Comment by mih** [comment]
I believe we can close this info issue now. Most of these vocabs are actively used now.
