### ISSUE TITLE
Notes on the Data Catalog – Provenance – Access Control (DCPAC) Ontology

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/datalad-concepts#63]
## _dcpac_: Data Catalog – Provenance – Access Control (DCPAC) Ontology

Access at: https://ceur-ws.org/Vol-2757/SSWS2020_paper5.pdf

### Builds on / Imports
- _dcat_:  [Data Catalog ontology](https://www.w3.org/TR/vocab-dcat-3/)
- _prov_: [Provenance Ontology](https://www.w3.org/TR/prov-o/)
- _skos_: [Simple Knowledge Organization System](https://www.w3.org/TR/skos-reference/)
- (_dcmterms_: [Dublin Core DCMI Metadata Terms](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/))
- _dpa_: [DCAT – PROV-O Alignment (DPA) Ontology](https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat-prov.ttl)
- _odrl_: [Open Digital Rights Language (ODRL) Ontology](https://www.w3.org/ns/odrl/2/)

### Description of useful concepts

- The DCPAC ontology aligns the DCAT ontology with the ODRL ontology by declaring the classes
`dcat:Distribution` and `dcat:Resource` to be subclasses of `odrl:Asset`. With `odrl:Asset` representing a resource
or a collection of resources that are the subject of access authorization rules, this enables the definition of access control permissions for these DCAT classes and subclasses with the ODRL vocabulary.
- the DCPAC ontology extends the DCAT ontology by defining various types of `dcat:Dataset` subclasses, which allows for distinguishing different types of datasets in a data lake, such as raw data files, tabular data files, relational database and graph database resources.
- The PROV-O class `prov:Agent` is declared as subclass of `odrl:Party`, hence enabling all instances of `prov:Agent` to undertake roles in access control permissions.
- The DCPAC ontology defines new subclasses of `prov:Activity`, which allow for distinguishing different types of activities that created (`dcpac:GenerationActivity`) or modified (`dcpac:ModificationActivity`) a data lake resource.

### Graph

<img width="648" alt="Screenshot 2023-11-14 at 10 23 20" src="https://github.com/psychoinformatics-de/datalad-schema/assets/10141237/87ff4602-f39a-4650-865a-6df83d64ba24">

#### DCAT Entities
- The overall data catalog of the data lake is represented by one instance of class `dcat:Catalog`. It can contain many dcat:Dataset instances, one per resource in the data lake, e.g. raw data files, HBase or Hive tables, or RDF-based knowledge graphs.
- An instance of class `dcat:Distribution` models a specific representation of a dataset, comprising a specific serialization or schematic arrangement. Different distributions can exist for the same dataset, and are accessible via a URL (`dcat:downloadURL`).
- The data catalog and the datasets can each have several data distribution services (`dcat:DataDistributionService`), which are end-points that provide access. They are accessible via an endpoint URL
(`dcat:endpointURL`).

#### PROV-O Entities
- The PROV-O classes and properties are used for modeling the provenance of the data catalog and its datasets (both
declared as subclasses of `prov:Entity`), and for defining agents (e.g. person, software agent) they are attributed to (`prov:wasAttributedTo`) or that were involved in the activity of creating the dataset.
- Activities (`prov:Activity`) are initiated by agents (`prov:wasAssociatedWith`), create new Datasets (`prov:wasGeneratedBy`), have an start and end time, and can use other datasets as input (`prov:used`).

#### ODRL Entities
- Access control is defined by classes and properties from the ODRL ontology.
- An `odrl:Permission` can define an access rule for groups of agents (`odrl:PartyCollection`) to datasets, their distributions and/or data distribution services (`odrl:target`). 
- The allowed actions (`odrl:Action`), such as display, read, modify, delete, are defined as `skos:Concept` and attached via `odrl:action` object property.

#### SKOS Entities
SKOS finally is applied for defining the semantics of the content of a dataset. Therefore, the catalog refers to one or more sets of SKOS concepts (`skos:ConceptScheme`) that can be used for semantically tagging datasets. The defined SKOS tags can be either directly linked to a dataset (`dcat:theme`), or they can be bundled and linked as a collection (`skos:Collection`), which enables the definition and reuse of (large) sets of SKOS tags.

**Comment by mih** [comment]
Closing this info issue in favor of #149
