### ISSUE TITLE
JSON-LD context generated from `datalad-dataset-components.yaml` incomplete

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-concepts#64]
It only contains the ontology parts, and not a single `SchemaElement` subclass.

No idea...

**Comment by jsheunis** [comment]
This is a bit unrelated, but also in the scope of "format X generated by LinkML is incomplete" and I wanted to make a record of this in our repo:

- https://github.com/linkml/linkml/issues/1618. At the moment no custom annotations flow through the jsonschema, and I picked this up some months ago when I was looking into using UI-ontology-based annotations that can be used for auto form generation

**Comment by mih** [comment]
We can close this. The schema is no longer relevant.
