### ISSUE TITLE
Produce full record for palmerpenguins dataset

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-concepts#85]
This is a non-DataLad dataset: https://allisonhorst.github.io/palmerpenguins/

The goal is to produce a comprehensive metadata record, compliant with the `dataset-version` schema.

This effort will yield the necessary extensions of the schema to support such a description.

Once complete, it will serve as a benchmark to consolidate (shrink) the ontology without loosing the necessary expressiveness.

The complete record will then be a suitable test case for the upcoming DataLad dataset generator.

**Comment by mih** [comment]
Some pointers:

A corresponding record from a previous effort: https://fz-juelich.sciebo.de/s/qlrTRVyeyC4Sfdl

Footer of https://lternet.edu/ has some grant info for an acknowledgment

**Comment by mslw** [comment]
> Footer of https://lternet.edu/ has some grant info for an acknowledgment

FTR, the "NSF-OPP" (Office of Polar Programs) funding entries found in the spreadsheet were entered based on the funding information in the [associated publication](https://doi.org/10.1371/journal.pone.0090081). They can be found in the NSF website, e.g. [0217282](https://www.nsf.gov/awardsearch/showAward?AWD_ID=0217282).
